Add new docker image build CI

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -50,3 +50,38 @@ jobs:
           elif [[ "${{ matrix.target }}" == "arm64" ]]; then
             ls -lh ./tasks-server-arm64
           fi
+  build-image:
+    name: build-docker-image
+    runs-on: ubuntu-latest
+    needs: build-linux
+    env:
+      DOCKER_BUILDKIT: 1
+      NODE_ENV: production
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Install curl
+        run: sudo apt-get update && sudo apt-get install -y curl
+      - name: Setup docker
+        uses: docker/setup-buildx-action@v3
+      - name: Setup standalone docker compose
+        run: |
+          curl -SL -o /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/v2.32.0/docker-compose-linux-x86_64
+          chmod +x /usr/local/bin/docker-compose
+          sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
+      - name: Compose build and up
+        run: docker-compose -p tasks --env-file .env.production up -d --build
+      - name: Wait for tasks-server to start
+        run: sleep 10
+      - name: Test endpoint
+        run: |
+          STATUS_CODE=$(curl -sL -o /dev/null -w "%{http_code}" http://localhost:9420/status)
+          if [ "$STATUS_CODE" -eq 200 ]; then
+            echo "OK"
+          else
+            echo "There was an error"
+            exit 1
+          fi
+      - name: Compose down
+        run: docker-compose -p tasks down
+        if: ${{ always() }}
